spring.application.name=SharimovAblay-TaskManagement
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/project_db
spring.datasource.username=project
spring.datasource.password=project

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

jwt.secret=SharimovAblaySuperSecretKey2026VeryLongAndSecure12345
jwt.expiration=86400000

logging.level.kz.ablaysharimov=DEBUG
logging.level.org.springframework.security=DEBUG